spring.application.name=midterm
spring.datasource.url = jdbc:postgresql://localhost:5501/midterm_devops
spring.datasource.username = daro
spring.datasource.password = daro1234

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect